### EXPLANATORY DATA ANALYSIS OF NORMAL TRANSCIENT DATA

In [9]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import openpyxl as xl
import os
import warnings
warnings.filterwarnings('ignore')

In [10]:
# Data Path
data_path = os.path.join(os.path.dirname(os.getcwd()), "data", "raw")
file_path = os.path.join(data_path, "normal_dataset.csv")
#Load the dataset
df = pd.read_csv(file_path)
# Display the first few rows of the dataset
df.head(10)

,nodenumber,x-coordinate,y-coordinate,z-coordinate,pressure,pressure-coefficient,density,velocity-magnitude,x-velocity,y-velocity,z-velocity,turb-kinetic-energy,turb-diss-rate,wall-shear,tailings-vof,timestep,label
0,1,25.000001,0.008344,-0.097383,21168.812960,34653.963120,2700.00006,0.000000,0.000000,0.000000,0.000000,0.036400,0.577750,38.203626,1.844108e-18,1,0
1,2,0.000000,0.012623,-0.096541,38814.917600,64472.464840,2700.00000,0.000000,0.000000,0.000000,0.000000,0.045525,44.802546,40.826937,4.000014e-01,1,0
2,3,50.000000,0.012623,-0.096541,1251.180643,2510.182354,2700.00000,0.000000,0.000000,0.000000,0.000000,0.039119,0.584892,40.845045,2.189194e-143,1,0
3,4,25.000000,-0.023607,-0.094895,20966.104920,34438.657840,2700.00000,0.000000,0.000000,0.000000,0.000000,0.036468,0.621301,38.334753,1.844973e-18,1,0
4,5,0.000000,-0.033333,-0.090946,38685.698180,64330.871500,2700.00000,0.000000,0.000000,0.000000,0.000000,0.045570,43.239824,40.693794,4.000014e-01,1,0
5,6,50.000000,-0.033333,-0.090946,1354.487389,2514.356787,2700.00000,0.000000,0.000000,0.000000,0.000000,0.038138,0.572188,40.550091,1.797694e-143,1,0
6,7,25.000001,-0.022285,-0.090455,21058.807410,34381.726390,2700.00000,3.263889,3.263316,-0.031496,-0.031253,0.036513,0.310620,0.000000,1.904717e-18,1,0
7,8,25.000001,0.006244,-0.085583,21199.150160,34610.857400,2700.00000,3.283000,3.282915,-0.005660,-0.016153,0.036214,0.284167,0.000000,1.917765e-18,1,0
8,9,50.000000,0.015056,-0.082753,0.000000,2094.493977,2700.00000,3.347043,3.340350,-0.029204,0.194177,0.036965,0.326557,0.000000,2.162621e-143,1,0
9,10,0.000000,0.015415,-0.081318,39563.257460,64880.611580,2700.00000,3.500000,3.500000,0.000000,0.000000,0.045937,84.647029,0.000000,4.000000e-01,1,0

In [11]:
# Get the summary statistics of the dataset
df.describe()

,nodenumber,x-coordinate,y-coordinate,z-coordinate,pressure,pressure-coefficient,density,velocity-magnitude,x-velocity,y-velocity,z-velocity,turb-kinetic-energy,turb-diss-rate,wall-shear,tailings-vof,timestep,label
count,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,102200.000000,1.022000e+05,102200.000000,102200.0
mean,73.500000,24.315068,0.002738,0.001175,19657.148237,32600.370694,2700.000001,2.478691,2.477680,0.001722,-0.001343,0.036312,24.397195,10.417679,3.806526e-01,350.500000,0.0
std,42.145787,19.833566,0.054443,0.054735,14681.898495,23682.338282,0.000019,1.524099,1.523507,0.050656,0.054788,0.007414,35.983536,17.016586,1.024321e-01,202.073377,0.0
min,1.000000,0.000000,-0.094941,-0.097383,0.000000,602.229160,2699.999920,0.000000,0.000000,-0.193954,-0.214380,0.023124,0.072722,0.000000,1.628369e-143,1.000000,0.0
25%,37.000000,0.000000,-0.036951,-0.041215,1278.818854,2369.576049,2700.000000,0.000000,0.000000,0.000000,0.000000,0.031571,0.209662,0.000000,3.999398e-01,175.750000,0.0
50%,73.500000,25.000000,0.006616,0.005573,19536.427015,31904.619055,2700.000000,3.361510,3.358792,0.000000,0.000000,0.034237,0.427391,0.000000,4.000000e-01,350.500000,0.0
75%,110.000000,50.000000,0.049997,0.045849,36752.331343,60713.784135,2700.000000,3.481479,3.480468,0.000000,0.001258,0.045937,45.039010,35.009601,4.001499e-01,525.250000,0.0
max,146.000000,50.000000,0.096835,0.096966,40473.336490,66166.540610,2700.000080,3.500000,3.500000,0.182147,0.194830,0.047165,84.647029,42.524073,5.083254e-01,700.000000,0.0

In [12]:
# Print the column names
df.columns

Index(['nodenumber', 'x-coordinate', 'y-coordinate', 'z-coordinate',
       'pressure', 'pressure-coefficient', 'density', 'velocity-magnitude',
       'x-velocity', 'y-velocity', 'z-velocity', 'turb-kinetic-energy',
       'turb-diss-rate', 'wall-shear', 'tailings-vof', 'timestep', 'label'],
      dtype='str')

In [13]:
# Get the shape of the dataset
df.shape

(102200, 17)

In [14]:
# Check for duplicates
print(df.columns[df.columns.duplicated()].tolist())

[]

In [15]:
# Check for the data types of each column
df.dtypes

nodenumber                int64
x-coordinate            float64
y-coordinate            float64
z-coordinate            float64
pressure                float64
pressure-coefficient    float64
density                 float64
velocity-magnitude      float64
x-velocity              float64
y-velocity              float64
z-velocity              float64
turb-kinetic-energy     float64
turb-diss-rate          float64
wall-shear              float64
tailings-vof            float64
timestep                  int64
label                     int64
dtype: object