### EXPLANATORY DATA ANALYSIS

#### Importing necessary libraries

In [1]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

### Importing the three datasets

In [2]:
# Data Path
data_path = os.path.join(os.path.dirname(os.getcwd()), "data", "raw")
sensor_data_file_path = os.path.join(data_path, "sensor_point_dataset_raw.csv")

In [3]:
# Load normal dataset
#Load the dataset
df = pd.read_csv(sensor_data_file_path)
# Display the first few rows of the dataset
df.head(10)

,timestep,node_a_pressure,velocity_a,tke_a,tdr_a,wall_shear_a,tailings_vof_a,node_b_pressure,velocity_b,tke_b,...,tailings_vof_c,label,effect_factor,pressure_drop_ab,pressure_drop_bc,pressure_drop_ac,dp_dt_a,dp_dt_b,dp_dt_c,flow_velocity
0,1,35793.499725,2.534141,0.034635,24.489446,11.197253,0.401012,19965.653843,2.474028,0.036128,...,0.406641,2,0.25,15827.845883,15575.231918,31403.077800,0.000000,0.000000,0.000000,2.474028
1,2,36620.208522,2.484805,0.038275,25.658411,10.641124,0.405089,20589.416498,2.421521,0.032585,...,0.409813,2,0.25,16030.792024,15994.695900,32025.487923,1653.417594,1247.525311,408.597347,2.421521
2,3,36251.794105,2.473708,0.034279,25.294662,9.484428,0.398871,20946.810911,2.531422,0.038077,...,0.399888,2,0.25,15304.983194,17127.536499,32432.519693,-736.828834,714.788826,-1550.892373,2.531422
3,4,35694.151655,2.478258,0.032199,27.022206,9.489620,0.393614,19637.008191,2.406712,0.038060,...,0.400838,2,0.25,16057.143465,15738.459191,31795.602655,-1115.284899,-2619.605441,158.549176,2.406712
4,5,35834.383052,2.467021,0.037261,22.894842,10.660725,0.400522,19776.413014,2.442424,0.034550,...,0.393732,2,0.25,16057.970038,16735.675964,32793.646002,280.462794,278.809648,-1715.623898,2.442424
5,6,36787.297566,2.569537,0.035647,23.439768,10.250242,0.398309,19106.601335,2.521981,0.035643,...,0.395355,2,0.25,17680.696231,15387.375912,33068.072143,1905.829027,-1339.623359,1356.976745,2.521981
6,7,36144.736489,2.485088,0.034797,24.908137,10.644589,0.395470,20094.551930,2.449309,0.038831,...,0.409765,2,0.25,16050.184559,15517.116567,31567.301126,-1285.122155,1975.901189,1716.419880,2.449309
7,8,35566.008814,2.496601,0.034091,24.837599,10.843902,0.395164,19447.852780,2.483421,0.034976,...,0.405673,2,0.25,16118.156034,16189.028932,32307.184967,-1157.455349,-1293.398300,-2637.223031,2.483421
8,9,36058.571722,2.555000,0.033721,24.339944,9.959091,0.393493,20766.372402,2.433175,0.029676,...,0.400670,2,0.25,15292.199319,16918.814662,32211.013981,985.125815,2637.039245,1177.467786,2.433175
9,10,36087.612877,2.511439,0.037675,25.088742,10.973236,0.402177,19771.627334,2.479944,0.033220,...,0.389187,2,0.25,16315.985542,15385.574766,31701.560308,58.082310,-1989.490136,1076.989657,2.479944

### Verify Column Consistency

In [4]:
#Print the shape of each
print(f"Normal data: {df.shape}")

Normal data: (31500, 28)

In [5]:
# Checking their datatypes
print("="*80)
print("Normal data types")
print("="*80)
print(df.dtypes)

================================================================================
Normal data types
================================================================================
timestep              int64
node_a_pressure     float64
velocity_a          float64
tke_a               float64
tdr_a               float64
wall_shear_a        float64
tailings_vof_a      float64
node_b_pressure     float64
velocity_b          float64
tke_b               float64
tdr_b               float64
wall_shear_b        float64
tailings_vof_b      float64
node_c_pressure     float64
velocity_c          float64
tke_c               float64
tdr_c               float64
wall_shear_c        float64
tailings_vof_c      float64
label                 int64
effect_factor       float64
pressure_drop_ab    float64
pressure_drop_bc    float64
pressure_drop_ac    float64
dp_dt_a             float64
dp_dt_b             float64
dp_dt_c             float64
flow_velocity       float64
dtype: object

### Dataset Overview

In [6]:
# Get the summary statistics of the dataset
df.describe()

,timestep,node_a_pressure,velocity_a,tke_a,tdr_a,wall_shear_a,tailings_vof_a,node_b_pressure,velocity_b,tke_b,...,tailings_vof_c,label,effect_factor,pressure_drop_ab,pressure_drop_bc,pressure_drop_ac,dp_dt_a,dp_dt_b,dp_dt_c,flow_velocity
count,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000,...,3.150000e+04,31500.00000,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000,31500.000000
mean,350.500000,36512.151484,2.419638,0.036476,24.907439,11.069532,0.401851,21034.263238,2.490511,0.037113,...,3.975664e-01,1.00000,0.184444,15477.888245,17109.255716,32587.143961,1.296603,-0.400513,-1.845079,2.490511
std,202.075596,1449.457076,0.372980,0.002882,3.717327,4.534840,0.011289,3744.848054,0.171186,0.003592,...,2.688716e-02,0.81651,0.280643,4093.291689,3796.419777,1709.101921,1327.717787,1394.527070,1358.768087,0.171186
min,1.000000,34676.165823,0.000000,0.026500,16.885318,7.589720,0.364572,18660.099359,1.912035,0.026119,...,2.189194e-143,0.00000,0.000000,-7601.707294,13743.300720,29766.897583,-4413.856734,-4354.836043,-4185.872229,1.912035
25%,175.750000,35867.073861,2.423551,0.034650,23.056482,9.995836,0.396304,19789.642309,2.423849,0.034877,...,3.936697e-01,0.00000,0.000000,15451.456720,15607.345752,31607.710513,-843.796760,-971.715033,-899.946054,2.423849
50%,350.500000,36227.467194,2.475410,0.036360,24.446919,10.405609,0.400919,20171.497599,2.479663,0.036691,...,3.992245e-01,1.00000,0.000000,16055.753917,16130.343606,32156.667890,0.065470,0.000000,-0.000014,2.479663
75%,525.250000,36598.726242,2.523018,0.038162,25.956913,10.821718,0.406812,20605.963230,2.531817,0.038862,...,4.043675e-01,2.00000,0.250000,16674.113887,16848.245337,32874.626082,884.102072,926.730244,833.983961,2.531817
max,700.000000,45000.000000,2.769596,0.045784,44.802546,40.826997,0.446441,43078.003325,3.317132,0.050000,...,5.082733e-01,2.00000,0.900000,26012.574493,39182.052449,41877.241687,4068.270519,5913.172246,4614.860421,3.317132