### Feature engineering for model training

In [5]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from pathlib import Path
import os

In [7]:
# Data loading
raw_data_path= Path.cwd().parent/ "data" / "raw"
file_path = os.path.join(raw_data_path, "sensor_point_dataset_raw.csv")
df = pd.read_csv(file_path)
df.head(10)

,timestep,node_a_pressure,velocity_a,tke_a,tdr_a,wall_shear_a,tailings_vof_a,node_b_pressure,velocity_b,tke_b,...,tailings_vof_c,label,effect_factor,pressure_drop_ab,pressure_drop_bc,pressure_drop_ac,dp_dt_a,dp_dt_b,dp_dt_c,flow_velocity
0,1,35793.499725,2.534141,0.034635,24.489446,11.197253,0.401012,19965.653843,2.474028,0.036128,...,0.406641,2,0.25,15827.845883,15575.231918,31403.077800,0.000000,0.000000,0.000000,2.474028
1,2,36620.208522,2.484805,0.038275,25.658411,10.641124,0.405089,20589.416498,2.421521,0.032585,...,0.409813,2,0.25,16030.792024,15994.695900,32025.487923,1653.417594,1247.525311,408.597347,2.421521
2,3,36251.794105,2.473708,0.034279,25.294662,9.484428,0.398871,20946.810911,2.531422,0.038077,...,0.399888,2,0.25,15304.983194,17127.536499,32432.519693,-736.828834,714.788826,-1550.892373,2.531422
3,4,35694.151655,2.478258,0.032199,27.022206,9.489620,0.393614,19637.008191,2.406712,0.038060,...,0.400838,2,0.25,16057.143465,15738.459191,31795.602655,-1115.284899,-2619.605441,158.549176,2.406712
4,5,35834.383052,2.467021,0.037261,22.894842,10.660725,0.400522,19776.413014,2.442424,0.034550,...,0.393732,2,0.25,16057.970038,16735.675964,32793.646002,280.462794,278.809648,-1715.623898,2.442424
5,6,36787.297566,2.569537,0.035647,23.439768,10.250242,0.398309,19106.601335,2.521981,0.035643,...,0.395355,2,0.25,17680.696231,15387.375912,33068.072143,1905.829027,-1339.623359,1356.976745,2.521981
6,7,36144.736489,2.485088,0.034797,24.908137,10.644589,0.395470,20094.551930,2.449309,0.038831,...,0.409765,2,0.25,16050.184559,15517.116567,31567.301126,-1285.122155,1975.901189,1716.419880,2.449309
7,8,35566.008814,2.496601,0.034091,24.837599,10.843902,0.395164,19447.852780,2.483421,0.034976,...,0.405673,2,0.25,16118.156034,16189.028932,32307.184967,-1157.455349,-1293.398300,-2637.223031,2.483421
8,9,36058.571722,2.555000,0.033721,24.339944,9.959091,0.393493,20766.372402,2.433175,0.029676,...,0.400670,2,0.25,15292.199319,16918.814662,32211.013981,985.125815,2637.039245,1177.467786,2.433175
9,10,36087.612877,2.511439,0.037675,25.088742,10.973236,0.402177,19771.627334,2.479944,0.033220,...,0.389187,2,0.25,16315.985542,15385.574766,31701.560308,58.082310,-1989.490136,1076.989657,2.479944

In [8]:
# Check for duplicates
df[df.duplicated()]

Empty DataFrame
Columns: [timestep, node_a_pressure, velocity_a, tke_a, tdr_a, wall_shear_a, tailings_vof_a, node_b_pressure, velocity_b, tke_b, tdr_b, wall_shear_b, tailings_vof_b, node_c_pressure, velocity_c, tke_c, tdr_c, wall_shear_c, tailings_vof_c, label, effect_factor, pressure_drop_ab, pressure_drop_bc, pressure_drop_ac, dp_dt_a, dp_dt_b, dp_dt_c, flow_velocity]
Index: []

[0 rows x 28 columns]

- We have no data point that is duplicated.